chinese_learning_platform/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import MindMapViewSet, ChineseWordViewSet, AddWordToMindMapView, DeckPerformanceViewSet, \
    WordPerformanceViewSet, SentenceListCreateView, SentenceRetrieveUpdateDestroyView, ChineseWordFavoriteView, \
    ChineseWordFavoriteStatusView
app_name='api'

router = DefaultRouter()
router.register(r'mindmaps', MindMapViewSet)
router.register(r'words', ChineseWordViewSet)
router.register(r'deck-performance', DeckPerformanceViewSet, basename='deckperformance')
router.register(r'word-performance', WordPerformanceViewSet, basename='word-performance')

urlpatterns = [
    path('', include(router.urls)),
    path('mindmaps/<int:mindmap_id>/add-word/', AddWordToMindMapView.as_view(), name='add-word-to-mindmap'),
    path('word-performance/<int:pk>/correct/', WordPerformanceViewSet.as_view({'post': 'mark_correct'}),
         name='mark-correct'),
    path('word-performance/<int:pk>/incorrect/', WordPerformanceViewSet.as_view({'post': 'mark_incorrect'}),
         name='mark-incorrect'),

    path('sentences/', SentenceListCreateView.as_view(), name='sentence-list-create'),
    path('sentences/<int:pk>/', SentenceRetrieveUpdateDestroyView.as_view(), name='sentence-detail'),

    path('words/<int:pk>/favorite/', ChineseWordFavoriteView.as_view(), name='word-favorite'),
    path('words/<int:word_id>/favorite-status/', ChineseWordFavoriteStatusView.as_view(),
         name='favorite-status'),
]

chinese_learning_platform/chinese_learning_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('', include('frontend.urls')),
    path('word/', include('wordpages.urls')),
    path('accounts/', include('users.urls')),
    path('lessons/', include('lessons.urls')),
    path('mindmaps/', include('mindmaps.urls')),
    path('schedule/', include('schedule.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:  # Ensure to import settings if not already done
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),  # Include Debug Toolbar URLs
    ]

chinese_learning_platform/frontend/urls.py
from django.urls import path, include
from .views import IndexPageView, UserDecksView, AllWordsView, UserWordsView, ReviewWordsView, UserFavoritesView
from .views_deck import DeckDetailView, EditDeckView, ReviewDeckView, TestDeckView, AddDeckView, CreateDeckView, DeleteDeckView

app_name = 'frontend'

urlpatterns = [
    path('', IndexPageView.as_view(), name='index'),
    path('user/<str:username>/decks/', UserDecksView.as_view(), name='user_decks'),
    path('all-words/', AllWordsView.as_view(), name='all_words'),
    path('user-words/', UserWordsView.as_view(), name='user_words'),
    path('review-words/', ReviewWordsView.as_view(), name='review_words'),
    path('user/favorites/', UserFavoritesView.as_view(), name='user_favorites'),

    path('deck/<int:pk>/', DeckDetailView.as_view(), name='deck_detail'),
    path('deck/edit/<int:pk>/', EditDeckView.as_view(), name='edit_deck'),
    path('deck/review/<int:pk>/', ReviewDeckView.as_view(), name='review_deck'),
    path('deck/test/<int:pk>/', TestDeckView.as_view(), name='test_deck'),
    path('deck/add/<int:pk>/', AddDeckView.as_view(), name='add_deck'),
    path('deck/create/', CreateDeckView.as_view(), name='create_deck'),
    path('deck/<int:pk>/delete/', DeleteDeckView.as_view(), name='delete_deck'),
]

chinese_learning_platform/lessons/urls.py
from django.urls import path
from .views import (
    LessonListView, LessonCreateView, LessonUpdateView, LessonDetailView,
    ReadingTextListView, ReadingTextCreateView,
    HomeworkListView, HomeworkCreateView, HomeworkUpdateView, HomeworkDeleteView,
    LexicalExerciseListView, LexicalExerciseCreateView, ReadingTextUpdateView, ReadingTextDeleteView,
    EditLexicalExerciseView, LexicalExerciseDeleteView
)

app_name = "lessons"

urlpatterns = [
    path('', LessonListView.as_view(), name='lesson_list'),
    path('add/', LessonCreateView.as_view(), name='add_lesson'),
    path('<int:lesson_id>/', LessonDetailView.as_view(), name='lesson_detail'),
    path('<int:lesson_id>/edit/', LessonUpdateView.as_view(), name='edit_lesson'),

    path('<int:lesson_id>/reading_texts/', ReadingTextListView.as_view(), name='readingtext_list'),
    path('<int:lesson_id>/reading-text/add/', ReadingTextCreateView.as_view(), name='add_readingtext'),
    path('<int:lesson_id>/reading-text/<int:pk>/edit/', ReadingTextUpdateView.as_view(), name='edit_readingtext'),
    path('<int:lesson_id>/reading-text/<int:pk>/delete/', ReadingTextDeleteView.as_view(), name='readingtext_delete'),

    path('<int:lesson_id>/homeworks/', HomeworkListView.as_view(), name='homework_list'),
    path('<int:lesson_id>/homework/add/', HomeworkCreateView.as_view(), name='add_homework'),
    path('<int:lesson_id>/homework/<int:pk>/edit/', HomeworkUpdateView.as_view(), name='edit_homework'),
    path('<int:lesson_id>/homework/<int:pk>/delete/', HomeworkDeleteView.as_view(), name='homework_delete'),

    path('<int:lesson_id>/lexical_exercises/', LexicalExerciseListView.as_view(), name='lexicalexercise_list'),
    path('<int:lesson_id>/lexical-exercise/add/', LexicalExerciseCreateView.as_view(), name='add_lexicalexercise'),
    path('<int:lesson_id>/lexical_exercise/<int:pk>/edit/', EditLexicalExerciseView.as_view(), name='edit_lexicalexercise'),
    path('<int:lesson_id>/lexical_exercise/<int:pk>/delete/', LexicalExerciseDeleteView.as_view(), name='lexicalexercise_delete'),
]

chinese_learning_platform/mindmaps/urls.py
from django.urls import path
from .views import MindMapListView, MindMapDetailView, MindMapCreateView
app_name = 'mindmaps'
urlpatterns = [
    path('', MindMapListView.as_view(), name='mindmap-list'),
    path('<int:pk>/', MindMapDetailView.as_view(), name='mindmap-detail'),
    path('create/', MindMapCreateView.as_view(), name='mindmap-create'),
]

chinese_learning_platform/users/urls.py
from django.urls import path, include, reverse_lazy
from .forms import CustomUserCreationForm
from django.views.generic.edit import CreateView

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path(
        'registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=CustomUserCreationForm,
            success_url=reverse_lazy('frontend:index'),
        ),
        name='registration',
    ),
]

templates/includes/auth_script.html
<script>
    const isAuthenticated = {% if current_user.is_authenticated %}true{% else %}false{% endif %};
</script>

templates/includes/card_table.html
<div class="container">
    <div class="table-container">
        <div class="table-row heading">
            <div class="row-item">Слово</div>
            <div class="row-item">Произношение</div>
            <div class="row-item">Перевод</div>
            {% if current_user.is_authenticated %}
            <div class="row-item">Текущий процент</div>
            {% endif %}
        </div>
        {% for item in to_test %}
        <div class="table-row">
            <input type="hidden" class="perf-id" value="{{ item.performance.id }}">
            <input type="hidden" class="card-id" value="{{ item.word.id }}">
            <div class="row-item chinese"
                 data-id="{{ item.performance.word.id }}"
                 data-pinyin="{{ item.performance.word.pinyin }}"
                 data-meaning="{{ item.performance.word.meaning }}">
                <div class="simplified">{{ item.performance.word.simplified }}</div>
            </div>
            <div class="row-item pinyin">{{ item.word.pinyin }}</div>
            <div class="row-item meaning">{{ item.word.meaning }}</div>
            {% if current_user.is_authenticated %}
            <div class="row-item percent">
                {{ item.performance.accuracy_percentage_display }}%
            </div>
            {% endif %}
        </div>
        {% endfor %}
    </div>
</div>

templates/includes/deck_performance.html
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    let myChart;

    window.addEventListener("load", function () {
        const body = document.body;
        const gridColor = (body.classList.contains('dark-theme')) ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.1)';
        const rawDates = {{ deck_data.test_dates | safe }};

        const currentYear = new Date().getFullYear();
        const formattedDates = rawDates.map(date => {
            const dateObj = new Date(date);
            const options = { day: 'numeric', month: 'long' };
            let formattedDate = dateObj.toLocaleDateString('en-US', options);

            if (dateObj.getFullYear() !== currentYear) {
                formattedDate += ` ${dateObj.getFullYear()}`;
            }
            return formattedDate;
        });
        const chartData = {
            labels: formattedDates,
            datasets: [{
                label: 'Процент правильных ответов',
                data: {{ deck_data.percent_correct | safe }},
                backgroundColor: 'rgba(54, 162, 235, 0.2)',
                borderColor: 'rgba(54, 162, 235, 1)',
                borderWidth: 1
            }]
        };

        // Checking if Chart.js and data are properly set up
        if (!chartData.labels.length || !chartData.datasets[0].data.length) {
            console.error('No data available for chart');
            return;
        }
    const maxYValue = Math.max(100, ...{{ deck_data.percent_correct | safe }}) + 10;
        const ctx = document.getElementById('myChart').getContext('2d');
        myChart = new Chart(ctx, {
            type: 'bar',
            data: chartData,
            options: {
                minBarLength: 5,
                maxBarThickness: 30,
                scales: {
                    x: {
                    grid: {color: gridColor}},
                    y: {
                    grid: {color: gridColor},
                        beginAtZero: true,
                        max: maxYValue}
            }
        }});

        // Ensure the chart is visible
        document.getElementById('chart-container').style.display = 'block';

        // Handle chart clicks to show detailed info
        myChart.canvas.addEventListener('click', function (event) {
            const activePoints = myChart.getElementsAtEventForMode(event, 'index', {intersect: true}, true);
            if (activePoints.length > 0) {
                const index = activePoints[0].index;
                const date = chartData.labels[index];
                const percentage = chartData.datasets[0].data[index];
                const wrongAnswers = {{ deck_data.wrong_answers | safe }}[index];

                const infoContainer = document.getElementById('info-container');
                let wrongAnswersHTML = wrongAnswers.map(answer => `
                                <span class="wrong-answer chinese"
                                      data-id="${answer.id}"
                                      data-pinyin="${answer.pinyin}"
                                      data-meaning="${answer.meaning}"
                                      >
                                    ${answer.simplified}
                                </span>
                        `).join(', '); // Join to create a single string from the array

                // Create the infoContainer HTML
                infoContainer.innerHTML = `
                    Дата: ${date},
                    Процент: ${percentage}%,
                    Неправильные ответы: ${wrongAnswersHTML}
                `;
                const wrongAnswerElements = document.querySelectorAll('.wrong-answer.chinese');
                wrongAnswerElements.forEach(element => {
                    element.addEventListener('click', () => showModal(element)); // Call showModal on click
                });
            }
        });
    });
</script>

<div class="container">
    <div id="chart-container" style="display:none;">
        <canvas id="myChart"></canvas>
    </div>
    <div id="info-container"></div>
</div>

templates/includes/flashcard.html
<div class="form-check form-switch">
    <input class="form-check-input" type="checkbox" id="togglePinyin" checked>
    <label class="form-check-label" for="togglePinyin">Показывать пиньин на карточке с ответом</label>
</div>
<div id="flashcard" class="flashcard" style="margin-bottom: 30%">
    <div class="card-header" style="width:100%">
        <div class="progress">
            <div id="quiz-progress" class="progress-bar bg-info" role="progressbar" style="width: 0%;"
                 aria-valuenow="0"></div>
        </div>
    </div>
    <div class="card-body">
        <div class="front">
            <h6 id="front-pinyin">mama</h6>
            <h6 class="card-title" id="front-translation">сущ. мама</h6>
        </div>
        <div class="back" style="display: none;">
            <h5 id="back-character"
                style="font-family: KaiTi, STKaiti, DFKai-SB, BiauKai, Arial !important; font-size:80px;">妈妈</h5>
            <div class="pinyin-container">
                <h6 id="back-pinyin" class="pinyin" style="margin-top: 10px;">mama</h6>
            </div>
        </div>
        <div class="button-container">
            <button id="quiz-right" class="btn btn-outline-secondary">Верно</button>
            <button id="quiz-wrong" class="btn btn-outline-secondary"> Неверно</button>
        </div>
        <div class="button-container">
            <button id="quiz-restart" class="btn btn-outline-secondary">Перезапустить тест</button>
        </div>
    </div>
</div>

templates/includes/header.html
{% load static %}
<header class="header container d-flex flex-wrap align-items-center justify-content-md-between py-3 mb-4">
    <div class="col-md-3 mb-2 mb-md-0 left-header">
        <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
            <svg class="bi" width="40" height="32" role="img" aria-label="Bootstrap">
                <use xlink:href="#bootstrap"></use>
            </svg>
        </a>
    </div>

    {% include 'includes/nav.html' %}
    <div class="col-md-3 text-end" style="display: flex; flex-direction: row; align-items: center;">
        {% include 'includes/theme_switch.html' %}
        {% if request.user.is_anonymous %}
        <a class="btn btn-outline-primary me-2 {% if '/login/' in request.path %} active {% endif %}"
           href="{% url 'users:login' %}">Войти</a>
        <a class="btn btn-outline-primary me-2 {% if '/registration/' in request.path %} active {% endif %}"
           href="{% url 'users:registration' %}">Регистрация</a>
        {% else %}
        <form method="post" action="{% url 'users:logout' %}" style="display:inline;">
            {% csrf_token %}
            <button type="submit" class="nav-link btn btn-link" style="background:none; border:none;">
                Выйти
            </button>
        </form>
        {% endif %}
    </div>
</header>

templates/includes/nav.html
{% load static %}
<ul class="nav col-12 col-md-auto justify-content-center mb-md-0">
    <li><a href="{% url 'frontend:index' %}" class="nav-link px-2">Дом</a></li>
    {% if request.user.is_authenticated %}
    <li class="nav-item dropdown">
        <a class="nav-link px-2 dropdown-toggle" href="#" id="navbarDropdown" role="button"
           data-bs-toggle="dropdown"
           aria-expanded="false">
            Профиль
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'frontend:user_decks' user.username %}">Колоды</a></li>
            <li><a class="dropdown-item" href="{% url 'schedule:calendar' %}">Расписание</a></li>
            <li><a class="dropdown-item" href="{% url 'lessons:lesson_list'%}">Уроки Китайского</a></li>
        </ul>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link px-2 dropdown-toggle" href="#" id="navbarDropdown" role="button"
           data-bs-toggle="dropdown"
           aria-expanded="false">
            Слова
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'frontend:user_words'%}">Изученные слова</a></li>
            <li><a class="dropdown-item" href="{% url 'frontend:all_words' %}">Слова</a></li>
            <li><a class="dropdown-item" href="{% url 'frontend:user_favorites'%}">Избранные слова</a></li>
            <li><a class="dropdown-item" href="{% url 'mindmaps:mindmap-list' %}">МайндМапы</a></li>
        </ul>
    </li>
    {% else %}
    <li class="nav-item dropdown">
        <a class="nav-link px-2 dropdown-toggle" href="#" id="navbarDropdown" role="button"
           data-bs-toggle="dropdown"
           aria-expanded="false">
            Слова
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <!--            <li><a class="dropdown-item" href="{% url 'frontend:user_words'%}">Изученные слова</a></li>-->
            <li><a class="dropdown-item" href="{% url 'frontend:all_words' %}">Слова</a></li>
            <!--            <li><a class="dropdown-item" href="{% url 'frontend:user_favorites'%}">Избранные слова</a></li>-->
            <li><a class="dropdown-item" href="{% url 'lessons:lesson_list'%}">Уроки Китайского</a></li>
            <li><a class="dropdown-item" href="{% url 'mindmaps:mindmap-list' %}">МайндМапы</a></li>
        </ul>
    </li>
    {% endif %}
</ul>

templates/includes/pagination.html
{% comment %}
File: templates/includes/pagination.html
{% endcomment %}

{% load my_template_tags %}

{% if page_obj.paginator.num_pages > 1 %}
<div class="pagination-container">
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?{% param_replace page=page_obj.previous_page_number %}">&laquo;</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">&laquo;</span>
                </li>
            {% endif %}

            {% if page_obj.number > 5 %}
                <li class="page-item">
                    <a class="page-link" href="?{% param_replace page=1 %}">1</a>
                </li>
                <li class="page-item disabled">
                    <span class="page-link">...</span>
                </li>
            {% endif %}

            {% for page_num in page_obj.paginator.page_range %}
                {% if page_num >= page_obj.number|add:-4 and page_num <= page_obj.number|add:5 %}
                    {% if page_num == page_obj.number %}
                        <li class="page-item active">
                            <span class="page-link">{{ page_num }}</span>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?{% param_replace page=page_num %}">{{ page_num }}</a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}

            {% if page_obj.number < page_obj.paginator.num_pages|add:-5 %}
                <li class="page-item disabled">
                    <span class="page-link">...</span>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?{% param_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
                </li>
            {% endif %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?{% param_replace page=page_obj.next_page_number %}">&raquo;</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">&raquo;</span>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endif %}

templates/includes/performance_table.html
<div class="table-container">
    <div class="table-row heading">
        <div class="row-item">Слово</div>
        <div class="row-item">Произношение</div>
        <div class="row-item">Перевод</div>
        <div class="row-item">Статистика</div>
        {% if '/deck/' in request.path or '/user-words/' in request.path %}
            <div class="row-item percent-header" onclick="sortTable('accuracy_percentage')">Процент</div>
            <div class="row-item date-header" onclick="sortTable('next_review_date')">Повторение</div>
        {% else %}
            <div class="row-item percent-header">Процент</div>
            {% if '/user-words/' in request.path %}
                <div class="row-item date-header">Повторение</div>
            {% endif %}
        {% endif %}
    </div>

    {% for performance in performances %}
        {% include "includes/performance_table_row.html" %}
    {% endfor %}
</div>

templates/includes/performance_table_row.html
<div class="table-row">
    <div class="row-item">
        <div class="chinese"
             data-id="{{ performance.word.id }}"
             data-pinyin="{{ performance.word.pinyin }}"
             data-meaning="{{ performance.word.meaning }}">
            {{ performance.word.simplified }}
        </div>
    </div>
    <div class="row-item">{{ performance.word.pinyin }}</div>
    <div class="row-item">{{ performance.word.meaning }}</div>
    <div class="row-item">{{ performance }}</div>
    <div class="row-item percent">{{ performance.accuracy_percentage_display }}%</div>

    {% if '/deck/' in request.path or '/user-words/' in request.path %}
        <!-- Hidden element for sorting -->
        <div class="row-item next-review-date" style="display: none;">
            {{ performance.next_review_date|date:"c" }}  <!-- Render the actual date here -->
        </div>
        <!-- Visible element for users -->
        <div class="row-item">
            {% if performance.next_review_date < now %}
                {{ performance.next_review_date|timesince }} ago
            {% else %}
                in {{ performance.next_review_date|timeuntil }}
            {% endif %}
        </div>
    {% endif %}
</div>

templates/includes/progress_bar.html
<div class="progress progress-slim">
    <div class="progress-bar {{ progress_color }}" role="progressbar"
         aria-valuenow="{{ percent }}" aria-valuemin="0" aria-valuemax="100"
         style="width: {{ percent }}%;"></div>
</div>

templates/includes/user_favorites_search_form.html
<form method="GET" action="{% url 'frontend:user_favorites' %}">
    <div class="input-group mb-3">
        {{ search_form.search }}
        <div class="input-group-append">
            <select class="form-control" name="hsk_levels" multiple>
                {% for level in '0123456'|make_list %}
                    <option value="{{ level }}" {% if level in request.GET.hsk_levels %}selected{% endif %}>HSK {{ level }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="input-group-append">
            <button class="btn btn-primary" type="submit">Поиск</button>
        </div>
        <div class="input-group-append">
            <button class="btn btn-secondary" type="button" id="repeatButton">Повторить</button>
        </div>
    </div>
</form>
<script>
document.addEventListener('DOMContentLoaded', function () {
    const repeatButton = document.getElementById('repeatButton');

    repeatButton.addEventListener('click', function () {
        // Get current form action URL
        const url = "{% url 'frontend:review_words' %}";

        // Create a URLSearchParams object to hold the existing query parameters
        const params = new URLSearchParams(window.location.search);

        // Get sort_by and sort_order from existing query parameters, or use default values if they don't exist
        const sortBy = params.get('sort_by');
        const sortOrder = params.get('sort_order');

        if (sortBy) {
            params.set('sort_by', sortBy);
        }

        if (sortOrder) {
            params.set('sort_order', sortOrder);
        }

        // Append the specific parameters for the repeat action
        params.set('sort_by', sortBy);
        params.set('sort_order', sortOrder);

        // Redirect to the new URL with the query parameters
        window.location.href = `${url}?${params.toString()}`;
    });
});
</script>

templates/includes/user_search_form.html
{% comment %}
File: templates/includes/user_search_form.html
{% endcomment %}

<form method="GET" action="{% url 'frontend:user_words' %}">
    <div class="input-group mb-3">
        {{ search_form.search }}
        <div class="input-group-append">
            <select class="form-control" name="review_period">
                <option value="" {% if review_period == '' %}selected{% endif %}>All</option>
                <option value="last_week" {% if review_period == 'last_week' %}selected{% endif %}>Last Week</option>
                <option value="last_three_days" {% if review_period == 'last_three_days' %}selected{% endif %}>Last 3 Days</option>
                <option value="last_day" {% if review_period == 'last_day' %}selected{% endif %}>Last Day</option>
                <option value="zero" {% if review_period == 'zero' %}selected{% endif %}>Future</option>
                <option value="three_days" {% if review_period == 'three_days' %}selected{% endif %}>Next 3 Days</option>
                <option value="week" {% if review_period == 'week' %}selected{% endif %}>Next Week</option>
            </select>
        </div>
        <div class="input-group-append" style="margin-right: 0.5rem;">
            <select class="form-control" name="hsk_levels" multiple>
                {% for level in '0123456'|make_list %}
                    <option value="{{ level }}" {% if level in request.GET.hsk_levels %}selected{% endif %}>HSK {{ level }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="input-group-append">
            <button class="btn btn-primary" type="submit">Поиск</button>
        </div>
        <div class="input-group-append">
            <button class="btn btn-secondary" type="button" id="repeatButton">Повторить</button>
        </div>
    </div>
</form>

<script>
document.addEventListener('DOMContentLoaded', function () {
    const repeatButton = document.getElementById('repeatButton');

    repeatButton.addEventListener('click', function () {
        // Get current form action URL
        const url = "{% url 'frontend:review_words' %}";

        // Create a URLSearchParams object to hold the existing query parameters
        const params = new URLSearchParams(window.location.search);

        // Get sort_by and sort_order from existing query parameters, or use default values if they don't exist
        const sortBy = params.get('sort_by');
        const sortOrder = params.get('sort_order');

        if (sortBy) {
            params.set('sort_by', sortBy);
        }

        if (sortOrder) {
            params.set('sort_order', sortOrder);
        }

        // Redirect to the new URL with the query parameters
        window.location.href = `${url}?${params.toString()}`;
    });
});
</script>

templates/includes/word_table.html
<div class="table-container">
    <div class="table-row heading">
        <div class="row-item">Слово</div>
        <div class="row-item">Произношение</div>
        <div class="row-item">Перевод</div>
    </div>

    {% for word in words %}
    {% include "includes/word_table_row.html" %}
    {% endfor %}
</div>

templates/includes/word_table_row.html
<div class="table-row">
    <div class="row-item">
        <div class="chinese"
             data-id="{{ word.id }}"
             data-pinyin="{{ word.pinyin }}"
             data-meaning="{{ word.meaning }}">
            {{ word.simplified }}
        </div>
    </div>
    <div class="row-item">{{ word.pinyin }}</div>
    <div class="row-item">{{ word.meaning }}</div>
</div>